project/about/urls.py
import django.urls

import about.views

app_name = "about"

urlpatterns = [
    django.urls.path(
        "",
        about.views.DescriptionTemplateView.as_view(),
        name="main",
    ),
]

project/project/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import leaderboard.apps
import leaderboard.urls
import search.apps
import search.urls
import streetsport.apps

urlpatterns = [
    django.urls.path(
        "",
        django.urls.include(
            "homepage.urls",
        ),
        name="homepage",
    ),
    django.urls.path(
        "about/",
        django.urls.include(
            "about.urls",
        ),
        name="about",
    ),
    django.urls.path(
        "feedback/",
        django.urls.include(("feedback.urls")),
        name="feedback",
    ),
    django.urls.path(
        "games/",
        django.urls.include(("streetsport.urls")),
        name=streetsport.apps.StreetsportConfig.name,
    ),
    django.urls.path(
        "auth/",
        django.urls.include(("users.urls")),
        name="users",
    ),
    django.urls.path(
        "admin/",
        django.contrib.admin.site.urls,
    ),
    django.urls.path(
        "auth/",
        django.urls.include(django.contrib.auth.urls),
    ),
    django.urls.path(
        "search/",
        django.urls.include(search.urls),
        name=search.apps.SearchConfig.name,
    ),
    django.urls.path(
        "leaderboard/",
        django.urls.include(leaderboard.urls),
        name=leaderboard.apps.LeaderboardConfig.name,
    ),
]


if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include("debug_toolbar.urls"),
        ),
    )
    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

project/search/urls.py
import django.urls

import search.apps
import search.views

app_name = search.apps.SearchConfig.name

urlpatterns = [
    django.urls.path(
        "",
        search.views.SearchListView.as_view(),
        name="search",
    )
]

project/users/urls.py
import django.contrib.auth.forms
import django.contrib.auth.views
import django.urls

import users.forms
import users.views

__all__ = []


app_name = "users"

urlpatterns = [
    django.urls.path(
        "profile/<int:pk>/",
        users.views.ProfileDetailView.as_view(),
        name="profile",
    ),
    django.urls.path(
        "profile/",
        users.views.ProfileTemplateView.as_view(),
        name="profile-current",
    ),
    django.urls.path(
        "profile/edit/",
        users.views.ProfileEditFormView.as_view(),
        name="profile-edit",
    ),
    django.urls.path(
        "profile/delete/",
        users.views.UserDeleteView.as_view(),
        name="user-delete",
    ),
    django.urls.path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
            redirect_authenticated_user=True,
            authentication_form=users.forms.custom_auth_form(
                django.contrib.auth.forms.AuthenticationForm,
            ),
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(),
        name="logout",
    ),
    django.urls.path(
        "password_change/",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            form_class=users.forms.custom_auth_form(
                django.contrib.auth.forms.PasswordChangeForm,
            ),
        ),
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            form_class=users.forms.custom_auth_form(
                django.contrib.auth.forms.PasswordResetForm,
            ),
            success_url=django.urls.reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    django.urls.path(
        "reset/<uidb64>/<token>/",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            form_class=users.forms.custom_auth_form(
                django.contrib.auth.forms.SetPasswordForm,
            ),
            template_name="users/password_reset_confirm.html",
            success_url=django.urls.reverse_lazy(
                "users:password_reset_complete",
            ),
        ),
        name="password_reset_confirm",
    ),
    django.urls.path(
        "reset/done/",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    django.urls.path(
        "signup/",
        users.views.SignupFormView.as_view(
            redirect_authenticated_user=True,
        ),
        name="signup",
    ),
    django.urls.path(
        "activate/<token>/",
        users.views.ActivateRedirectView.as_view(),
        name="activate",
    ),
]

project/search/forms.py
__all__ = []

import django.forms


class SearchForm(django.forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form__input"

    search_value = django.forms.CharField(
        max_length=254, label="поиск игрока или команды"
    )

    class Meta:
        fields = ["search_value"]

project/search/views.py
__all__ = []

import django.shortcuts
import django.views
import django.views.generic

import search.forms
import streetsport.models
import users.models


class SearchListView(django.views.generic.FormView):
    template_name = "search/search.html"
    form_class = search.forms.SearchForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_value = context["form"].data["search-header"]
        context["users"] = users.models.User.objects.search_by_username(
            search_value,
        )
        context["teams"] = streetsport.models.Team.objects.search_by_title(
            search_value,
        )
        return context

project/templates/search/search.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
{% trans "search_title"|capfirst %}
{% endblock title %}

{% block content %}
{% get_media_prefix as media %}
<section class="search" data-media-url="{% get_media_prefix %}">
  <div class="search__body _container">
    <h1>{% trans "search_title"|capfirst %}</h1>
    <div class="section__content search__content">
      <ul class="search__items items">
        <li class="search__item item">
          <div class="search__wrapper">
            <div class="search__label">
              <label for="">игроки</label>
            </div>
            {% if users %}
            <div class="search__table">
              <table cellspacing="0" class="search-table table">
                <tr class="table__row table_header">
                  <th class="table__header row_num">
                    №
                  </th>
                  <th class="table__header">
                    Игрок
                  </th>
                </tr>
                {% for user in users %}
                  <tr class="table__row">
                    <td class="table__data row_num">
                    </td>
                    <td class="table__data table_data">
                      <div class="table__content">
                        <div class="table__thumb">
                          {% if user.avatar %}
                          <img src="{{ user.get_image_preview_x100.url }}" alt="{% trans 'avatar_img'|capfirst %}">
                          {% else %}
                          <img src="{% static 'img/default/avatar.svg' %}" alt="{% trans 'default_avatar_img'|capfirst %}">
                          {% endif %}
                        </div>
                        <a href="{% url 'users:profile' pk=user.id %}" class="table__text color_blue">
                          {{ user.username }}
                        </a>
                      </div>
                    </td>
                  </tr>
                {% endfor %}
              </table>
            </div>
            {% else %}
            <div class="search__null users_null">
              Нет пользователей
            </div>
            {% endif %}
          </div>
        </li>
        <li class="search__item item">
          <div class="search__wrapper">
            <div class="search__label">
              <label for="">команды</label>
            </div>
            {% if teams %}
            <div class="search__table">
              <table cellspacing="0" class="search-table table">
                <tr class="table__row table_header">
                  <th class="table__header row_num">
                    №
                  </th>
                  <th class="table__header">
                    Команда
                  </th>
                </tr>
                {% for team in teams %}
                <tr class="table__row">
                  <td class="table__data row_num">
                  </td>
                  <td class="table__data table_data">
                    <div class="table__content">
                      <div class="table__thumb">
                        {% if team.avatar %}
                        <img src="{{ team.get_image_preview_x100.url }}" alt="{% trans 'avatar_img'|capfirst %}">
                        {% else %}
                        <img src="{% static 'img/default/team.svg' %}" alt="{% trans 'default_team_img'|capfirst %}">
                        {% endif %}
                      </div>
                      <a href="{% url 'streetsport:team' pk=team.id %}" class="table__text color_blue">
                        {{ team.title }}
                      </a>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </table>
            </div>
            {% else %}
            <div class="search__null teams_null">
              Нет команд
            </div>
            {% endif %}
          </div>
        </li>

      </ul>
    </div>
  </div>
</section>
{% endblock content %}