project/about/urls.py
import django.urls

import about.views

app_name = "about"

urlpatterns = [
    django.urls.path(
        "",
        about.views.DescriptionTemplateView.as_view(),
        name="main",
    ),
]

project/feedback/urls.py
import django.urls

import feedback.views

app_name = "feedback"

urlpatterns = [
    django.urls.path(
        "",
        feedback.views.FeedbackCreateView.as_view(),
        name="feedback",
    ),
]

project/homepage/urls.py
import django.urls

import homepage.views

app_name = "homepage"
urlpatterns = [
    django.urls.path(
        "",
        homepage.views.HomeView.as_view(),
        name="main",
    ),
]

project/project/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import leaderboard.apps
import leaderboard.urls
import search.apps
import search.urls
import streetsport.apps

urlpatterns = [
    django.urls.path(
        "",
        django.urls.include(
            "homepage.urls",
        ),
        name="homepage",
    ),
    django.urls.path(
        "about/",
        django.urls.include(
            "about.urls",
        ),
        name="about",
    ),
    django.urls.path(
        "feedback/",
        django.urls.include(("feedback.urls")),
        name="feedback",
    ),
    django.urls.path(
        "games/",
        django.urls.include(("streetsport.urls")),
        name=streetsport.apps.StreetsportConfig.name,
    ),
    django.urls.path(
        "auth/",
        django.urls.include(("users.urls")),
        name="users",
    ),
    django.urls.path(
        "admin/",
        django.contrib.admin.site.urls,
    ),
    django.urls.path(
        "auth/",
        django.urls.include(django.contrib.auth.urls),
    ),
    django.urls.path(
        "search/",
        django.urls.include(search.urls),
        name=search.apps.SearchConfig.name,
    ),
    django.urls.path(
        "leaderboard/",
        django.urls.include(leaderboard.urls),
        name=leaderboard.apps.LeaderboardConfig.name,
    ),
]


if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include("debug_toolbar.urls"),
        ),
    )
    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

project/templates/includes/btn.html
<a href="{{ url|default:'#' }}" type="button" name="btn" id="btn" class="btn">{{ value }}</a>

project/templates/includes/filter_item.html
<div class="filters__filter filter btn">
  <div class="filter__content">
    
  </div>
</div>

project/templates/includes/footer.html
{% load static %}
{% load i18n %}

<footer>
  <div class="footer__body _container">
    <div class="footer__content">
      <a href="{% url 'homepage:main' %}" class="header__logo">
        <span class="color_red">Street</span> Спорт
      </a>
      <nav class="footer__navbar navbar">
        <ul class="navbar__items items">
          <li class="navbar__item item">
            <a class="navbar__link footer_link" id="about" href="{% url 'about:main' %}">
              {% trans "about"|capfirst %}
            </a>
          </li>
          <li class="navbar__item item">
            <a class="navbar__link footer_link" id="feedback" href="{% url 'feedback:feedback' %}">
              {% trans "feedback"|capfirst %}
            </a>
          </li>
        </ul>
      </nav>
    </div>
    <div class="footer__copyright copyright">
      © copyright, {% now "Y" %}
    </div>
  </div>
</footer>

project/templates/includes/form.html
{% load i18n %}

{% if form.non_field_errors %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}


{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

  
{% for field in form.visible_fields %}
<div class="form__field">
  {{ field.label_tag}}
  {{ field }}

  {% if 'file' in field.widget_type %}
  <label class="form__field-wrapper" for="{{ field.auto_id }}">
    <div class="form__field-button">Выберите файлы:</div>
    <div class="form__field-content">Файл не выбран</div>
  </label>
  {% endif %}

  {% if form.is_bound and field.errors %}
    {% for error in field.errors %}
    <div class="invalid-feedback d-block">
      {{ error|escape }}
    </div>
    {% endfor %}
  {% endif %}

  {% if field.help_text and False %}
    <div class="form-text">{{ field.help_text }}</div>
  {% endif %}
</div>
{% endfor %}

project/templates/includes/game_order.html
{% load static %}
{% load i18n %}
<article class="matches__match match" data-game="{{ order.game.normalize_title }}" data-team-one="{{ order.team_one.normalize_title }}" data-team-two="{{ order.team_two.normalize_title }}">
	<div class="match__left match-team team-one">
		<div class="match-team__img">
			{% if order.team_one.avatar %}
			<img src="{{ order.team_one.get_image_preview_400x300.url }}" alt="{% trans 'team_img'|capfirst %}">
			{% else %}
			<div class="match-team__img-default">
				<img src="{% static 'img/default/team.svg' %}" alt="{% trans 'default_team_img'|capfirst %}">
			</div>
			{% endif %}
		</div>
		<div class="match__content">
			<div class="match-team__title">
				{{ order.team_one.title }}
			</div>
			<div class="match-team__teammates team-teammates">
				<ul class="team-teammates__items items">
					{% with team_teammates=order.team_one.teammates.all %}
						{% for teammate in team_teammates|slice:":3" %}
							<li class="team-teammates__item teammates__item item team-teammate">
								<div class="team-teammate__item">
									<div class="team-teammate__img">
										{% if teammate.avatar %}
										<img src="{{ teammate.get_image_preview_x100.url }}" alt="{% trans 'avatar_img'|capfirst %}">
										{% else %}
										<img src="{% static 'img/default/avatar.png' %}" alt="{% trans 'default_avatar_img'|capfirst %}">
										{% endif %}
									</div>
								</div>
							</li>
						{% endfor %}
						{% if team_teammates|length|add:"-3" > 0 %}
						<li class="team-teammates__item item teammates_count">
							<div class="team-teammate__item">
								+{{ team_teammates|length|add:"-3" }}
							</div>
						</li>
						{% endif %}
						{% for teammate in team_teammates %}
							<li data-username="{{ teammate.username }}" class="team__teammates-hidden team_teammates_hidden" hidden></li>
						{% endfor %}

					{% endwith %}
				</ul>
			</div>
		</div>
	</div>
	<div class="match__center match-decor">
		<div class="match-decor__game match-game">
			<div class="match-game__img">
				{% if order.game.icon %}
				<img src="{{ order.game.get_image_preview_x50.url }}" alt="match_game">
				{% else %}
				<img src="{% static 'img/default/sports.png' %}" alt="default_match_game">
				{% endif %}
			</div>
			<div class="match-game__wrapper">
				{{ order.game.title|capfirst }}
			</div>
		</div>
		<div class="match-decor__vs match-vs">
			<div class="match-vs__wrapper">
				VS
			</div>
		</div>
		<span class="match-decor__line"></span>
	</div>
	<div class="match__right match-team team-two">
		<div class="match-team__img">
			{% if order.team_two.avatar %}
			<img src="{{ order.team_two.get_image_preview_400x300.url }}" alt="{% trans 'team_img'|capfirst %}">
			{% else %}
			<div class="match-team__img-default">
				<img src="{% static 'img/default/team.svg' %}" alt="{% trans 'default_team_img'|capfirst %}">
			</div>
			{% endif %}
		</div>
		<div class="match__content">
			<div class="match-team__title">
				{{ order.team_two.title }}
			</div>
			<div class="match-team__teammates team-teammates">
				<ul class="team-teammates__items items">
					{% with team_teammates=order.team_two.teammates.all %}
						{% for teammate in team_teammates|slice:":3" %}
							<li class="team-teammates__item item team-teammate">
								<div class="team-teammate__item">
									<div class="team-teammate__img">
										{% if teammate.avatar %}
										<img src="{{ teammate.get_image_preview_x100.url }}" alt="{% trans 'avatar_img'|capfirst %}">
										{% else %}
										<img src="{% static 'img/default/avatar.png' %}" alt="{% trans 'default_avatar_img'|capfirst %}">
										{% endif %}
									</div>
								</div>
							</li>
						{% endfor %}
						{% if team_teammates|length|add:"-3" > 0 %}
						<li class="team-teammates__item item teammates_count">
							<div class="team-teammate__item">
								+{{ team_teammates|length|add:"-3" }}
							</div>
						</li>
						{% endif %}
						{% for teammate in team_teammates %}
							<li data-username="{{ teammate.username }}" class="team__teammates-hidden team_teammates_hidden" hidden></li>
						{% endfor %}

					{% endwith %}
				</ul>
			</div>
		</div>
	</div>
</article>

project/templates/includes/header.html
{% load static %}
{% load i18n %}

<header>
  <div class="header__main">
    <div class="header__body _container">
      <div class="header__content">
        <a href="{% url 'homepage:main' %}" class="header__logo">
          <span class="color_red">Street</span> Спорт
        </a>
        <nav class="header__navbar navbar">
          <ul class="navbar__items items">
            {% with view_name=request.resolver_match.view_name is_auth=request.user.is_authenticated %}
            <li class="navbar__item item">
              <a class="navbar__link {% if view_name == 'homepage:main' %}_active{% endif %}" href="{% url 'homepage:main' %}">
                {% trans "main"|capfirst %}
              </a>
            </li>
            <li class="navbar__item item">
              <a class="navbar__link {% if view_name == 'streetsport:orders' %}_active{% endif %}" href="{% url 'streetsport:orders' %}">
                {% trans "games"|capfirst %}
              </a>
            </li>
            <li class="navbar__item item">
              <a class="navbar__link {% if view_name == 'leaderboard:main' %}_active{% endif %}" href="{% url 'leaderboard:users' %}">
                {% trans "leaderboard"|capfirst %}
              </a>
            </li>
            {% if is_auth %}
            {% if user.is_superuser %}
              <li class="navbar__item item">
                <a class="navbar__link" href="{% url 'admin:index' %}">
                  {% trans "admin"|capfirst %}
                </a>
              </li>
            {% endif %}
            <li class="navbar__item item">
              <a class="navbar__link {% if view_name == 'users:profile:profile-current' %}_active{% endif %}" href="{% url 'users:profile' pk=request.user.id %}">
                {% trans "profile"|capfirst %}
              </a>
            </li>
            {% else %}
            <li class="navbar__item item">
              <a class="navbar__link {% if view_name == 'users:login' %}_active{% endif %}" href="{% url 'users:login' %}">
                {% trans "login"|capfirst %}
              </a>
            </li>
            <li class="navbar__item item">
              <a class="navbar__link {% if view_name == 'users:signup' %}_active{% endif %}" href="{% url 'users:signup' %}">
                {% trans "signup"|capfirst %}
              </a>
            </li>
            {% endif %}
            <li class="navbar__item item search_header_btn">
              <a class="navbar__link">
                <svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M24.5 26.25L16.625 18.375C16 18.875 15.2813 19.2708 14.4688 19.5625C13.6563 19.8542 12.7917 20 11.875 20C9.60417 20 7.6825 19.2133 6.11 17.64C4.5375 16.0667 3.75083 14.145 3.75 11.875C3.74917 9.605 4.53583 7.68333 6.11 6.11C7.68417 4.53667 9.60583 3.75 11.875 3.75C14.1442 3.75 16.0663 4.53667 17.6413 6.11C19.2163 7.68333 20.0025 9.605 20 11.875C20 12.7917 19.8542 13.6562 19.5625 14.4688C19.2708 15.2812 18.875 16 18.375 16.625L26.25 24.5L24.5 26.25ZM11.875 17.5C13.4375 17.5 14.7658 16.9533 15.86 15.86C16.9542 14.7667 17.5008 13.4383 17.5 11.875C17.4992 10.3117 16.9525 8.98375 15.86 7.89125C14.7675 6.79875 13.4392 6.25167 11.875 6.25C10.3108 6.24833 8.98292 6.79542 7.89125 7.89125C6.79958 8.98708 6.2525 10.315 6.25 11.875C6.2475 13.435 6.79458 14.7633 7.89125 15.86C8.98792 16.9567 10.3158 17.5033 11.875 17.5Z" fill="#2796FD"/>
                </svg>
              </a>
            </li>
            {% endwith %}
          </ul>
        </nav>
      </div>
    </div>
  </div>
  <div class="header__search search-header">
    <div class="search__body _container">
      <div class="search__content">
        <form class="form search_form" method="post" action="{% url 'search:search' %}">
          {% csrf_token %}
          <div class="form__field">
            {% comment %}
              {{ form.label_tag }}
            {% endcomment %}
            <label for="searchHeader">поиск игрока или команды:</label>
            
            <div class="filter-field__wrapper">
              <input type="search" name="search-header" maxlength="254" class="form__input" required="" id="searchHeader">

              {% comment %}
                {{ field.field }}
              {% endcomment %}
            
              <button type="submit" class="filter-field__searchicon search_btn">
                <img src="{% static 'img/icons/search.svg' %}" alt="{% trans "search_btn"|capfirst %}">
              </button>

              {% comment %}
              <a href="" class="filter-field__searchicon search_btn">
                <img src="{% static 'img/icons/search.svg' %}" alt="{% trans "search_btn"|capfirst %}">
              </a>
              {% endcomment %}
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</header>

project/templates/includes/submit_btn.html
<input type="submit" name="submit" id="submit" class="btn" value="{{ value|default:'Отправить'}}">