project/about/urls.py
import django.urls

import about.views

app_name = "about"

urlpatterns = [
    django.urls.path(
        "",
        about.views.DescriptionTemplateView.as_view(),
        name="main",
    ),
]

project/homepage/urls.py
import django.urls

import homepage.views

app_name = "homepage"
urlpatterns = [
    django.urls.path(
        "",
        homepage.views.HomeView.as_view(),
        name="main",
    ),
]

project/project/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import leaderboard.apps
import leaderboard.urls
import search.apps
import search.urls
import streetsport.apps

urlpatterns = [
    django.urls.path(
        "",
        django.urls.include(
            "homepage.urls",
        ),
        name="homepage",
    ),
    django.urls.path(
        "about/",
        django.urls.include(
            "about.urls",
        ),
        name="about",
    ),
    django.urls.path(
        "feedback/",
        django.urls.include(("feedback.urls")),
        name="feedback",
    ),
    django.urls.path(
        "games/",
        django.urls.include(("streetsport.urls")),
        name=streetsport.apps.StreetsportConfig.name,
    ),
    django.urls.path(
        "auth/",
        django.urls.include(("users.urls")),
        name="users",
    ),
    django.urls.path(
        "admin/",
        django.contrib.admin.site.urls,
    ),
    django.urls.path(
        "auth/",
        django.urls.include(django.contrib.auth.urls),
    ),
    django.urls.path(
        "search/",
        django.urls.include(search.urls),
        name=search.apps.SearchConfig.name,
    ),
    django.urls.path(
        "leaderboard/",
        django.urls.include(leaderboard.urls),
        name=leaderboard.apps.LeaderboardConfig.name,
    ),
]


if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include("debug_toolbar.urls"),
        ),
    )
    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

project/users/urls.py
import django.contrib.auth.forms
import django.contrib.auth.views
import django.urls

import users.forms
import users.views

__all__ = []


app_name = "users"

urlpatterns = [
    django.urls.path(
        "profile/<int:pk>/",
        users.views.ProfileDetailView.as_view(),
        name="profile",
    ),
    django.urls.path(
        "profile/",
        users.views.ProfileTemplateView.as_view(),
        name="profile-current",
    ),
    django.urls.path(
        "profile/edit/",
        users.views.ProfileEditFormView.as_view(),
        name="profile-edit",
    ),
    django.urls.path(
        "profile/delete/",
        users.views.UserDeleteView.as_view(),
        name="user-delete",
    ),
    django.urls.path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
            redirect_authenticated_user=True,
            authentication_form=users.forms.custom_auth_form(
                django.contrib.auth.forms.AuthenticationForm,
            ),
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(),
        name="logout",
    ),
    django.urls.path(
        "password_change/",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            form_class=users.forms.custom_auth_form(
                django.contrib.auth.forms.PasswordChangeForm,
            ),
        ),
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            form_class=users.forms.custom_auth_form(
                django.contrib.auth.forms.PasswordResetForm,
            ),
            success_url=django.urls.reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    django.urls.path(
        "reset/<uidb64>/<token>/",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            form_class=users.forms.custom_auth_form(
                django.contrib.auth.forms.SetPasswordForm,
            ),
            template_name="users/password_reset_confirm.html",
            success_url=django.urls.reverse_lazy(
                "users:password_reset_complete",
            ),
        ),
        name="password_reset_confirm",
    ),
    django.urls.path(
        "reset/done/",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    django.urls.path(
        "signup/",
        users.views.SignupFormView.as_view(
            redirect_authenticated_user=True,
        ),
        name="signup",
    ),
    django.urls.path(
        "activate/<token>/",
        users.views.ActivateRedirectView.as_view(),
        name="activate",
    ),
]

project/users/models.py
import pathlib
import uuid

import django.contrib.auth.models
import django.db.models
from django.utils.translation import gettext_lazy as _
import sorl.thumbnail

import streetsport.models
import users.validators

__all__ = []


class UserManager(django.contrib.auth.models.UserManager):
    CONONICAL_DOMAINS = {
        "yandex.ru": "ya.ru",
    }
    DOTS = {
        "ya.ry": "-",
        "gmail.com": "",
    }

    @classmethod
    def normalize_email(cls, email):
        email = super().normalize_email(email).lower()
        try:
            email_name, domain_part = email.rsplit("@", 1)
            email_name, *_ = email_name.split("+", 1)
            domain_part = cls.CONONICAL_DOMAINS.get(domain_part, domain_part)
            email_name = email_name.replace(
                ".",
                cls.DOTS.get(domain_part, "."),
            )
        except ValueError:
            pass
        else:
            email = f"{email_name}@{domain_part}"

        return email

    def by_mail(self, email):
        return self.get_queryset().get(email=self.normalize_email(email))

    def search_by_username(self, username):
        return (
            self.get_queryset()
            .filter(
                username__unaccent__icontains=username,
            )
            .order_by(User.username.field.name)
        )


class User(django.contrib.auth.models.AbstractUser):
    def get_path_image(self, filename):
        ext = pathlib.Path(filename).suffix
        return f"users/{self.id}/avatar{ext}"

    objects = UserManager()

    username = django.db.models.CharField(
        _("username"),
        max_length=32,
        unique=True,
        help_text=_("username_field_help"),
        validators=[
            users.validators.UsernameValidator(),
        ],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )

    email = django.db.models.EmailField(
        _("email address"),
        blank=True,
        unique=True,
    )

    bio = django.db.models.TextField(
        _("biography"),
        max_length=4000,
        help_text=_("bio_field_help"),
        blank=True,
        null=True,
    )
    birthday = django.db.models.DateField(
        _("birthday"),
        help_text=_("birthday_field_help"),
        validators=[users.validators.birthday_validator],
        null=True,
        blank=True,
    )
    avatar = sorl.thumbnail.ImageField(
        _("avatar"),
        help_text=_("avatar_field_help"),
        upload_to=get_path_image,
        null=True,
        blank=True,
    )
    tg_link = django.db.models.CharField(
        _("tg_link"),
        validators=[users.validators.TgLinkValidator()],
        help_text=_("tg_link_field_help"),
        max_length=44,
        blank=True,
        null=True,
    )
    rating = django.db.models.PositiveSmallIntegerField(
        _("rating"),
        help_text=_("rating_field_help"),
        default=0,
    )

    lead_team = django.db.models.OneToOneField(
        streetsport.models.Team,
        on_delete=django.db.models.SET_NULL,
        verbose_name=_("lead_team"),
        help_text=_("lead__team_field_help"),
        related_name="lead",
        related_query_name="lead",
        blank=True,
        null=True,
    )
    team = django.db.models.ForeignKey(
        streetsport.models.Team,
        on_delete=django.db.models.SET_NULL,
        verbose_name=_("team"),
        help_text=_("team_field_help"),
        related_name="teammates",
        related_query_name="teammates",
        blank=True,
        null=True,
    )

    def get_image_preview_x100(self, obj=None):
        return sorl.thumbnail.get_thumbnail(
            obj or self.avatar,
            "100x100",
            crop="center",
            quality=51,
        )

    def get_image_preview_x1000(self, obj=None):
        return sorl.thumbnail.get_thumbnail(
            obj or self.avatar,
            "1000x1000",
            crop="center",
            quality=51,
        )

    class Meta(django.contrib.auth.models.AbstractUser.Meta):
        ordering = ["rating", "username"]
        swappable = "AUTH_USER_MODEL"


class Image(django.db.models.Model):
    def get_path_image(self, filename):
        ext = pathlib.Path(filename).suffix
        return f"users/{self.user_id}/{uuid.uuid4()}{ext}"

    user = django.db.models.ForeignKey(
        User,
        on_delete=django.db.models.CASCADE,
        verbose_name=_("user"),
        help_text=_("user_field_help"),
        related_name="images",
        related_query_name="images",
    )
    image = sorl.thumbnail.ImageField(
        _("image"),
        upload_to=get_path_image,
        help_text=_("image_field_help"),
    )

    class Meta:
        verbose_name = _("user_image")
        verbose_name_plural = _("user_images")

    def __str__(self):
        return pathlib.Path(self.image.path).stem

project/users/forms.py
import django.contrib.auth.forms

import users.models

__all__ = []


def custom_auth_form(form):
    class CustomForm(form):
        def __init__(self, *args, **kwargs) -> None:
            super().__init__(*args, **kwargs)
            self.label_suffix = ""
            for field in self.visible_fields():
                field.field.widget.attrs["class"] = "form__input"

    return CustomForm


class SignUpForm(django.contrib.auth.forms.UserCreationForm):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form__input"

    class Meta(django.contrib.auth.forms.UserCreationForm.Meta):
        model = users.models.User
        fields = (
            model.username.field.name,
            model.email.field.name,
        )


class ProfileEditForm(django.contrib.auth.forms.UserChangeForm):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form__input"

        self.fields["avatar"].widget.attrs["class"] = "form__input input_file"

    class Meta(django.contrib.auth.forms.UserChangeForm.Meta):
        model = users.models.User
        fields = [
            users.models.User.avatar.field.name,
            users.models.User.username.field.name,
            users.models.User.first_name.field.name,
            users.models.User.last_name.field.name,
            users.models.User.birthday.field.name,
            users.models.User.bio.field.name,
            users.models.User.tg_link.field.name,
        ]

project/users/views.py
import django.conf
import django.contrib.auth
import django.contrib.auth.mixins
import django.contrib.messages
import django.core.mail
import django.core.signing
import django.db.models
import django.forms
import django.http
import django.template.loader
import django.urls
from django.utils.translation import gettext_lazy as _
import django.views.generic

import streetsport.models
import users.forms
import users.models


__all__ = []


class ProfileEditFormView(django.views.generic.UpdateView):
    success_message = _("profile_edit_success")
    form_class = users.forms.ProfileEditForm
    template_name = "users/profile_edit.html"
    success_url = django.urls.reverse_lazy("users:profile-current")

    def get_object(self, *args, **kwargs):
        return self.request.user


class SignupFormView(django.views.generic.FormView):
    redirect_authenticated_user = True
    form_class = users.forms.SignUpForm
    template_name = "users/signup.html"
    success_url = django.urls.reverse_lazy("users:login")

    def dispatch(self, request, *args, **kwargs):
        if (
            self.redirect_authenticated_user
            and self.request.user.is_authenticated
        ):
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. "
                    "Check that your LOGIN_REDIRECT_URL doesnt point "
                    "to a login page.",
                )

            return django.http.HttpResponseRedirect(redirect_to)

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        if django.conf.settings.DEFAULT_USER_IS_ACTIVE:
            user.is_active = True
            user.save()
            django.contrib.auth.login(self.request, user)
            return super().form_valid(form)

        token = django.core.signing.dumps(form.cleaned_data)

        django.core.mail.send_mail(
            subject="Activate your account",
            message=django.template.loader.render_to_string(
                "users/signup_email.html",
                {"token": token},
            ),
            from_email=django.conf.settings.EMAIL_ADMIN,
            recipient_list=[user.email],
        )
        django.contrib.messages.success(
            self.request,
            _("message_signup_success"),
        )
        return super().form_valid(form)


class ProfileTemplateView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.TemplateView,
):
    template_name = "users/profile.html"

    def get_context_data(self, **kwargs):
        user = self.request.user
        user_top = users.models.User.objects.aggregate(
            user_top=django.db.models.Count(
                "id",
                filter=django.db.models.Q(rating__gte=user.rating),
            ),
        )
        if user.team:
            team_top = streetsport.models.Team.objects.aggregate(
                team_top=django.db.models.Count(
                    "id",
                    filter=django.db.models.Q(rating__gte=user.team.rating),
                ),
            )
            kwargs.update(team_top)

        kwargs.update(user_top)
        context = super().get_context_data(**kwargs)
        context["user"] = user
        return context


class ProfileDetailView(django.views.generic.DetailView):
    template_name = "users/profile.html"
    queryset = users.models.User.objects.all()

    def get_context_data(self, **kwargs):
        user = kwargs.get("object")
        user_top = self.queryset.aggregate(
            user_top=django.db.models.Count(
                "id",
                filter=django.db.models.Q(rating__gte=user.rating),
            ),
        )
        if user.team:
            team_top = streetsport.models.Team.objects.aggregate(
                team_top=django.db.models.Count(
                    "id",
                    filter=django.db.models.Q(rating__gte=user.team.rating),
                ),
            )
            kwargs.update(team_top)

        kwargs.update(user_top)
        return super().get_context_data(**kwargs)


class UserDeleteView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.RedirectView,
):
    url = django.urls.reverse_lazy("homepage:main")

    def get(self, request, *args, **kwargs):
        request.user.delete()
        return super().get(request, *args, **kwargs)


class ActivateRedirectView(django.views.generic.RedirectView):
    django.views.generic.TemplateView
    url = django.urls.reverse_lazy("homepage:main")
    template_name = "users/signup.html"

    def get_redirect_url(self, *args, **kwargs):
        try:
            data = django.core.signing.loads(kwargs.get("token"))
        except django.core.signing.BadSignature:
            raise django.http.Http404

        form = users.forms.SignUpForm(data)
        if not form.is_valid():
            django.contrib.messages.success(
                self.request,
                _("message_activate_error"),
            )
            return super().get_redirect_url(*args, **kwargs)

        user = form.save()
        django.contrib.auth.login(self.request, user)
        django.contrib.messages.success(
            self.request,
            _("message_activate_success"),
        )

        return super().get_redirect_url(*args, **kwargs)

project/templates/users/login.html
{% extends "base.html" %}
{% load i18n %}


{% block title %}
  {% trans "login_title"|capfirst %}
{% endblock title %}

{% block content %}
<section class="login">
  <div class="login__body _container">
    <h1>{% trans "login_title"|capfirst %}</h1>
    <div class="section__content login__content">
      {% if form.is_multipart %}
        <form class="form" enctype="multipart/form-data" method="post">
      {% else %}
        <form class="form" method="post">
      {% endif %}
        {% csrf_token %}
      
        {% include "includes/form.html" %}
          
        <div class="form__button">
          {% include "includes/submit_btn.html" with value="Войти" %}
          <a class="form__link" href="{% url "users:signup" %}">{% trans "no_account"|capfirst %}? <span class="color_blue">{% trans "register_text"|capfirst %}</span></a>
        </div>
        <div class="form__extra">
          <a class="form__link" href="{% url "users:password_reset" %}">{% trans "forgot_password"|capfirst %}? <span class="color_blue">{% trans "reset_password_text"|capfirst %}</span></a>
        </div> 
      </form>
    </div>
  </div>
</section>
{% endblock content %}

project/templates/users/password_change.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "password_change_title"|capfirst %}
{% endblock title %}


{% block content %}
  <div class="row justify-content-center">
      <div class="col-12 col-md-6 col-lg-7">
        <form method="post">
          {% csrf_token %}
          {% include "includes/form.html" with be_button=True form=form %}
        </form>
      </div>
  </div>
{% endblock content %}

project/templates/users/password_change_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "success"|capfirst %}
{% endblock title %}


{% block content %}
<div class="jumbotron">
    <div class="container">
      <h1 class="display-3">{% trans "password_change_done_text"|capfirst %}</h1>
      <p><a class="btn btn-primary btn-lg" href="{% url 'homepage:main' %}" role="button">{% trans "home"|capfirst %} &raquo;</a></p>
    </div>
</div>
{% endblock content %}

project/templates/users/password_reset.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "reset_title"|capfirst %}
{% endblock title %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-12 col-md-6 col-lg-7">
      <form method="post">
        {% csrf_token %}
        {% include "includes/form.html" with be_button=True form=form %}
      </form>
  </div>
</div>
{% endblock content %}

project/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "success"|capfirst %}
{% endblock title %}

{% block content %}
  <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">{% trans "password_reset_complite_text"|capfirst %}</h1>
        <p><a class="btn btn-primary btn-lg" href="{% url 'homepage:main' %}" role="button">{% trans "home"|capfirst %} &raquo;</a></p>
      </div>
  </div>
{% endblock content %}

project/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "reset_title"|capfirst %}
{% endblock title %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-12 col-md-6 col-lg-7">
      <form method="post">
        {% csrf_token %}
        {% include "includes/form.html" with be_button=True form=form %}
      </form>
  </div>
</div>
{% endblock content %}

project/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "success"|capfirst %}
{% endblock title %}

{% block content %}
<div class="jumbotron">
    <div class="container">
      <h1 class="display-3">{% trans "password_reset_done_text"|capfirst %}</h1>
      <p><a class="btn btn-primary btn-lg" href="{% url 'homepage:main' %}" role="button">{% trans "home"|capfirst %} &raquo;</a></p>
    </div>
</div>
{% endblock content %}

project/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
{% trans "profile_title"|capfirst %}
{% endblock title %}

{% block content %}
{% get_media_prefix as media %}
<section class="profile" data-media-url="{% get_media_prefix %}">
  <div class="matches__body _container">
    <div class="section__title">
      <h1>
        {% trans "profile_title"|capfirst %}
      </h1>
      {% if request.user == user %}
      <div class="section__title-btns">
        <div class="section__title-btn btn_logout icon_btn">
          {% url 'users:logout' as url %}
          {% include 'includes/btn.html' with value='Выйти' url=url %}
        </div>
        <div class="section__title-btn btn_delete">
          {% url 'users:user-delete' as url %}
          {% include 'includes/btn.html' with value='Удалить аккаунт' url=url %}
        </div>
        <div class="section__title-btn btn_edit icon_btn">
          {% url 'users:profile-edit' as url %}
          {% include 'includes/btn.html' with value='Редактировать' url=url %}
        </div>
      </div>
      {% endif %}
    </div>
    <div class="section__content profile__content">
      <div class="profile__wrapper info_wrapper">
        <div class="profile__map info_img">
          {% if user.avatar %}
            <img src="{{ user.get_image_preview_x1000.url }}" alt="{% trans 'avatar_img'|capfirst %}">
          {% else %}
            <img src="{% static 'img/default/avatar.svg' %}" alt="{% trans 'default_avatar_img'|capfirst %}">
          {% endif %}
          <div class="profile__tabs tabs">
            <ul class="tabs__items items">
              <li class="tabs__item item">
                <a href="{% url 'leaderboard:users' %}" class="tab single_top">
                  <div class="tab__wrapper">
                    <div class="tab__title">
                      single top
                    </div>
                    <div class="tab__content">
                      <div class="tab__text filter_link filter">
                        {% if user_top %}
                          #{{ user_top }}
                        {% else %}
                          -
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </a>
              </li>
              {% if user.team %}
              <li class="tabs__item item">
                <a href="{% url 'leaderboard:teams' %}" class="tab team_top">
                  <div class="tab__wrapper">
                    <div class="tab__title">
                      team top
                    </div>
                    <div class="tab__content">
                      <div class="tab__text filter_link filter">
                        {% if team_top %}
                          #{{ team_top }}
                        {% else %}
                          -
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </a>
              </li>
              <li class="tabs__item item">
                <a href="{% url 'streetsport:team' 1 %}" class="tab team_tab">
                  <div class="tab__wrapper">
                    <div class="tab__title">
                      team
                    </div>
                    <div class="tab__content">
                      <div class="tab__text filter_link filter">
                        {{ user.team.title }}
                      </div>
                    </div>
                  </div>
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
        <div class="profile__info info_content">
          <div class="profile__field form__field info_field">
            <label for="">ник</label>
            <div class="profile__description info_text">
              {{ user.username }}
            </div>
          </div>
          <div class="profile__field form__field info_field">
            <label for="">почта</label>
            {% if user.first_name %}
              <a href="mailto:{{ user.email }}" class="profile__description info_text color_blue">
                {{ user.email }}
              </a>
            {% else %}
              -
            {% endif %}
          </div>
          <div class="profile__field form__field info_field">
            <label for="">имя</label>
            <div class="profile__description info_text">
              {% if user.first_name %}
                {{ user.first_name }}
              {% else %}
                -
              {% endif %}
            </div>
          </div>
          <div class="profile__field form__field info_field">
            <label for="">фамилия</label>
            <div class="profile__description info_text">
              {% if user.last_name %}
                {{ user.last_name }}
              {% else %}
                -
              {% endif %}
            </div>
          </div>
          <div class="profile__field form__field info_field">
            <label for="">день рождения</label>
            <div class="profile__description info_text">
              {% if user.birthday %}
                {{ user.birthday }}
              {% else %}
                -
              {% endif %}
            </div>
          </div>
          <div class="profile__field form__field info_field">
            <label for="">о себе</label>
            <div class="profile__description info_text">
              {% if user.bio %}
                {{ user.bio }}
              {% else %}
                -
              {% endif %}
            </div>
          </div>
          <div class="profile__field form__field info_field">
            <label for="">Telegram</label>
              {% if user.tg_link %}
                <a href="https://{{ user.tg_link }}" class="profile__description info_text color_blue">
                  {{ user.tg_link }}
                </a>
              {% else %}
                -
              {% endif %}
          </div>
          {% if request.user.is_authenticated %}
            {% if user.team and user != request.user%}
            <div class="profile__field form__field info_field">
              <div class="section__title-btn btn_add icon_btn">
                {% url 'streetsport:team-add' pk=user.id as url %}
                {% include 'includes/btn.html' with value='Пригласить в команду' url=url %}
              </div>
            </div>
            {% endif %}
            {% if not user.team and request.user == user %}
            <div class="profile__field form__field info_field">
              <div class="section__title-btn">
                {% url 'streetsport:team-create' as url %}
                {% include 'includes/btn.html' with value='Создать команду' url=url %}
              </div>
            </div>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

project/templates/users/profile_edit.html
{% extends "base.html" %}
{% load i18n %}


{% block title %}
  {% trans "profile_edit_title"|capfirst %}
{% endblock title %}

{% block content %}
<section class="profile">
  <div class="profile__body _container">
    <h1>  {% trans "profile_edit_title"|capfirst %}</h1>
    <div class="section__content profile__content">
      {% if form.is_multipart %}
        <form class="form" enctype="multipart/form-data" method="post">
      {% else %}
        <form class="form" method="post">
      {% endif %}
        {% csrf_token %}
      
        {% include "includes/form.html" %}
      
        <div class="form__button">
          {% include "includes/submit_btn.html" with value="Сохранить" %}
        </div>
      </form>
    </div>
  </div>
</section>
{% endblock content %}

project/templates/users/signup.html
{% extends "base.html" %}
{% load i18n %}


{% block title %}
  {% trans "register_title"|capfirst %}
{% endblock title %}

{% block content %}
<section class="register">
  <div class="register__body _container">
    <h1>{% trans "register_title"|capfirst %}</h1>
    <div class="section__content register__content">
      {% if form.is_multipart %}
        <form class="form" enctype="multipart/form-data" method="post">
      {% else %}
        <form class="form" method="post">
      {% endif %}
        {% csrf_token %}
      
        {% include "includes/form.html" %}
          
        <div class="form__button">
          {% include "includes/submit_btn.html" with value='Зарегистрироваться' %}
          <a class="form__link" href="{% url "users:login" %}">{% trans "has_account"|capfirst %}? <span class="color_blue">{% trans "login_text"|capfirst %}</span></a>
        </div>
        <div class="form__extra">
          <a class="form__link" href="{% url "users:password_reset" %}">
          Нажимая кнопку “Зарегистрироваться”, вы принимаете все 
          <span class="color_blue">условия конфиденциальности</span>
          и даете согласие на обработку своих персональных данных</a>
        </div> 
      </form>
    </div>
  </div>
</section>
{% endblock content %}

project/templates/users/signup_email.html
{% load i18n %}{% autoescape off %}
{% trans "activate_email_title" %}

{% trans "activate_email_text" %}
{% block reset_link %}
http://127.0.0.1:8000{% url 'users:activate' token %}
{% endblock %}
{% endautoescape %}